### ISSUE TITLE
Missing Dependencies from requirements.txt

### ISSUE THREAD

**Issue by stiliajohny** [Comcast/xGitGuard#3]
https://github.com/Comcast/xGitGuard/blob/ae109f5f91b2fa58ff9434e0ca6adbfbb3c0162c/requirements.txt

While executing the `/xgitguard/models/models.py` the library `pyyaml` is missing 
Would you consider adding this to the `requirements.txt`

**Comment by mmilutinovic013** [comment]
@stiliajohny  - Added a simple Pull Request for this. If it gets approved hopefully this should be resolved :).

**Comment by SARAVA01** [comment]
Added the required dependency in latest code. Thanks.
