### ISSUE TITLE
argparse inconsistancy on accepted vs recomened inputs 

### ISSUE THREAD

**Issue by stiliajohny** [Comcast/xGitGuard#4]
https://github.com/Comcast/xGitGuard/blob/ae109f5f91b2fa58ff9434e0ca6adbfbb3c0162c/xgitguard/models/model.py#L153-L154

The suggested help doesn't match the expected values, 
Would you consider changing this to 

```diff
 choices=["key", "cred"], 
- help="Pass the Data_Type as Cred or Key", 
+ help="Pass the Data_Type as cred or key", 
```
Or 

```diff
- choices=["key", "cred"], 
+ choices=["key", "cred", "Key", "Cred"], 
 help="Pass the Data_Type as Cred or Key", 

```

**Comment by SARAVA01** [comment]
Thanks for reporting. Same has been addressed in latest code. Thanks.
